### ISSUE TITLE
出现报错，wait networkidle meet error

### ISSUE THREAD

**Issue by Enceladus6** [nek0us/nonebot-plugin-gpt#7]
08-09 15:40:49 [DEBUG] ChatGPTWeb | flush mortygvjburba@outlook.com cf cookie OK!
08-09 15:40:59 [SUCCESS] nonebot | OneBot V11 3058592720 | [message.private.friend]: Message -110002963 from 1537175635 '你好'
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 1...
08-09 15:40:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
08-09 15:40:59 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
08-09 15:40:59 [DEBUG] nonebot | Running handler Dependent(call=_)
08-09 15:40:59 [DEBUG] nonebot | Handler Dependent(call=_) skipped
08-09 15:40:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56) running complete
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 2...
08-09 15:40:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
08-09 15:40:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
08-09 15:40:59 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
08-09 15:40:59 [DEBUG] nonebot | Running handler Dependent(call=_)
08-09 15:40:59 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
08-09 15:40:59 [DEBUG] nonebot | Running handler Dependent(call=check_pic)
08-09 15:40:59 [DEBUG] nonebot | Handler Dependent(call=_) skipped
08-09 15:40:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18) running complete
08-09 15:40:59 [DEBUG] nonebot | Handler Dependent(call=check_pic) skipped
08-09 15:40:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16) running complete
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 5...
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 19...
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 50...
08-09 15:40:59 [DEBUG] nonebot | Checking for matchers in priority 90...
08-09 15:40:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_gpt, lineno=128)
08-09 15:40:59 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_gpt, lineno=128)
08-09 15:40:59 [DEBUG] nonebot | Running handler Dependent(call=chat_handle)
08-09 15:41:05 [DEBUG] ChatGPTWeb | context mortygvjburba@outlook.com start!
08-09 15:41:05 [DEBUG] ChatGPTWeb | start!
08-09 15:41:06 [DEBUG] ChatGPTWeb | session mortygvjburba@outlook.com begin work
08-09 15:41:06 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com create new page to send msg
08-09 15:41:06 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com will register conversation api route
08-09 15:41:06 [DEBUG] ChatGPTWeb | send:你好
08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com begin create send msg cookie and header
08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com msg is new conversation
08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com will use page's _chatp
08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com will run page's _chatp.rS()
08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com wait networkidle meet error:Page.evaluate: Something went wrong. If this issue persists please contact us through our help center at help.openai.com.
i@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:354202
fetch@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:376792
async*fetch2@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:377161
async*post@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:378976
postAnonAware@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:379770
async*97834/d/n<@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:669990
promise callback*d@https://cdn.oaistatic.com/_next/static/chunks/pages/_app-43551a68c3e46a4c.js:38:669966
ty/<@https://cdn.oaistatic.com/_next/static/chunks/2092-c2c99599e8ab39bb.js:1:45604
uI@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:84056
oU@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:113104
oC@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:95921
r8@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:44813
95340/oI/<@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:111548
oI@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:111554
oS@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:94926
x@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:33:1365
T@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:33:1894
EventHandlerNonNull*26974@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:33:2063
k@debugger eval code line 226 > eval:8:110
22015@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:33:3825
k@debugger eval code line 226 > eval:8:110
95340@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:34
k@debugger eval code line 226 > eval:8:110
95295@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:129010
k@debugger eval code line 226 > eval:8:110
16254@https://cdn.oaistatic.com/_next/static/chunks/framework-ac719dc28fda7a28.js:9:128710
k@debugger eval code line 226 > eval:8:110
40190@https://cdn.oaistatic.com/_next/static/chunks/main-87d576f30e4bad32.js:1:6623
k@debugger eval code line 226 > eval:8:110
98353@https://cdn.oaistatic.com/_next/static/chunks/main-87d576f30e4bad32.js:1:15485
k@debugger eval code line 226 > eval:8:110
@https://cdn.oaistatic.com/_next/static/chunks/main-87d576f30e4bad32.js:1:108604
k.O@debugger eval code line 226 > eval:15:1519
@https://cdn.oaistatic.com/_next/static/chunks/main-87d576f30e4bad32.js:1:108626
h@debugger eval code line 226 > eval:15:11631
@debugger eval code line 226 > eval:15:11769
@debugger eval code line 226 > eval:15:11840
evaluate@debugger eval code:226:30
@debugger eval code:1:44

08-09 15:41:07 [DEBUG] ChatGPTWeb | mortygvjburba@outlook.com will run _proof
Error occurred in event listener
Traceback (most recent call last):
  File "E:\Enceladus6\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\playwright\_impl\_page.py", line 281, in _on_route
    handled = await route_handler.handle(route)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Enceladus6\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\playwright\_impl\_helper.py", line 290, in handle
    raise e
  File "E:\Enceladus6\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\playwright\_impl\_helper.py", line 285, in handle
    return await self._handle_internal(route)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Enceladus6\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\playwright\_impl\_helper.py", line 318, in _handle_internal
    await asyncio.ensure_future(coro_or_future)
  File "E:\Enceladus6\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\ChatGPTWeb\ChatGPTWeb.py", line 452, in route_handle
    proof = await page.evaluate(f'() => window._proof.Z.getEnforcementToken({json.dumps(json_result)})')
                                                                                        ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'json_result' where it is not associated with a value

**Comment by Enceladus6** [comment]
另外怎么让插件调用chrome而不是firefox，我用firefox无限卡真人验证

**Comment by nek0us** [comment]
遇到cf验证的话，需要更换一个更干净的代理ip。
目前没有提供更换浏览器的接口，因为chrome会比firefox收到更多的验证。

**Comment by Enceladus6** [comment]
目前我的代理手动登录，chrome 和edge 都可以，只有firefox不行

**Comment by nek0us** [comment]
> 目前我的代理手动登录，chrome 和edge 都可以，只有firefox不行

你可以`git clone` nek0us/ChatGPT这个项目，全局搜索替换项目内ChatGPTWeb.py文件中的firefox为chromium，然后在项目根目录`pip install -e .`后再试试
